version: "3.9"

services:

  dremio:
    image: dremio/dremio-oss:24.2
    container_name: dremio
    ports:  
      - 9047:9047 
      - 31010:31010 
      - 45678:45678
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  minioserver:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
    container_name: minio
    command: server /data --console-address ":9001"

  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"

  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_WEBSERVER_PORT: 8088
      SUPERSET_ADMIN_PASSWORD: admin
      SUPERSET_SECRET_KEY: xxxxx
    volumes:
      - ./superset:/app/superset_home
      - ./superset-init.sh:/app/superset-init.sh
    entrypoint: /app/superset-init.sh
    user: root

  jupyterlab:
    image: jupyter/datascience-notebook:latest
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
    command: start-notebook.sh --NotebookApp.token=''

networks:
  default:
    name: lakehousenet
    driver: bridge
